name: Python package

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: |
        pip3 install -e .[dev]
    - name: Lint with flake8
      run: |
        bash py-lint.sh
    - name: Check static types with mypy
      run: |
        mypy traceflow
        mypy tests
    - name: Test with pytest
      run: |
        pytest -sv tests
    - name: Generate coverage report
      run: |
        sudo apt-get install -y lcov
        coverage run -m pytest -sv tests
        coverage html --omit tests/*.py
        coverage lcov
        ls
        # Coverage is now in htmlcov/

